### PR TITLE
Add warning for object tree

### PR DESCRIPTION
**Pull request by anwa**
Some Warning at the option and in README

### CODE REVIEW

**Comment by Apollon77** [comment]
Great ide, thank you!

Any more stiff from your side, else I would release to latest tonight

**Comment by anwa** [comment]
Thanks Ingo,
i will go on with some issue fixing, but that needs some time.
Would be great if you release it tonight. I already installed the latest from git and it works fine so far.

**Comment by Apollon77** [comment]
Can you plese just get jewest git version again? I now fixed all issues where states were not set correctly sometimes and strange stuff happened. Also test is green again ... if yok then I release :-)

Thank you vory much for your participation and support!!

**Comment by anwa** [comment]
I guess i didn't got you :)
I synced my fork again, i also updated the Adapter in ioBroker from the latest git version.
Looks good so far...
At the moment, i'm testing everything on my tasmota Adapter. But tomorrow i will switch over to sonoff again and test the object tree there again.
@duczz has some issues, i will figure out tomorrow as well.
So maybe, better wait until tomorrow.

**Comment by Apollon77** [comment]
Ok I wait

**Pull request merged**
