### PR TITLE
LED controller support

### PR DESCRIPTION
**Pull request by gemu2015**
Sonoff b1, mahichome. arilux

### CODE REVIEW

**Comment by GermanBluefox** [comment]
Very comprehensive update. Thank you.
Just some points should be changed.

**Comment by gemu2015** [comment]
while i am a fairly good c programmer i am completely new to javascript. so change the necessary items or give me advice what needs to be changed.

however in the meantime Theo Arends released new Tasmota versions that support things directly i emulated like hue and channels.

in a future version of iobroker.sonoff  it would certainly be better to support Tasmota directly. i just dont know how long it will take until a stable 5.13 will be ready

One could change the emulated items names to the new ones of Tasmota, so that users would not have to change IDs later.

eg not red,green,blue,ww,cw but simply channel1 2 3 4 5 ???

console output of 5.12.0i =>

07:36:42 MQT: tele/sonoff/STATE = {"Time":"2018-03-29T07:36:42","Uptime":"0T00:00:13","Vcc":3.052,"POWER":"ON","Dimmer":69,"Color":"AFAFAF","HSBColor":"0,0,69","Channel":[69,69,69],"Scheme":0,"Fade":"OFF","Speed":1,"LedTable":"OFF","Wifi":{"AP":1,"SSId":"WLAN-7490","RSSI":82,"APMac":"CC:CE:1E:61:99:91"}}

**Comment by Apollon77** [comment]
Testing broken!
https://travis-ci.org/ioBroker/ioBroker.sonoff/jobs/358782979#L987

**Comment by Apollon77** [comment]
Sorry, but nodejs 4.x support is broken ... https://travis-ci.org/ioBroker/ioBroker.sonoff/jobs/359889964#L931

**Pull request merged**
