### PR TITLE
Update datapoints.js

### PR DESCRIPTION
**Pull request by mattreim**

### CODE REVIEW

**Comment by mcm1957** [comment]
@mattreim 

The unit for reactive Power is 'var' and not 'VAr'. I suggest to revert this change.

TodaySumExport - role should be most likely value.energy.produced (and not value.power.consumed)

power -> Leistiung -> W/kW
energy -> Energie -> Wh/kWh

today should all be value.energy.consumed
todaySumExport should be value.energy.produced
todaySumImport should be value.energy.consumed

Total should all be value.energy.consumed
Total_outSumExport should be value.energy.produced
Total_inSumImport should be value.energy.consumed

TotalStartTime should most likely be role date

Please check for other errors againts role specification. If upodating most errors should be corrected at once

**Comment by mattreim** [comment]
It's funny...

Sonoff

But it doesn't matter, thank you.

**Comment by mcm1957** [comment]
> It's funny...
> 
> Sonoff
> 
> But it doesn't matter, thank you.

OK, then please check other sources. I might be wrong too - although I nebver saw this mixed case until now. I guess theres some official site online stating the currect unit.

**Comment by mattreim** [comment]
You were right it is written in lower case.

**Pull request merged**
