### PR TITLE
support for autogenerate objects not in datapoints

### PR DESCRIPTION
**Pull request by gemu2015**
selective autogenerate objects by config/flags (default=1)

flags =
1 => tele/sonoff/SENSOR objects  are automatically generated (read only)
2 => tele/sonoff/STATE  objects  are automatically generated (read only)
4 => stat/sonoff/RESULT  objects  are automatically generated (read and write)

### CODE REVIEW

**Comment by GermanBluefox** [comment]
Thank you.
Can you resolve conflicts?

**Comment by gemu2015** [comment]
I cant see what github means with conflicts ?????

README.md => i just added the new version info
io-package-json => new version number + update info (no translation though)
datapoints.js => added some new datapoints for Tasmota 5.14
server.js => optimized led controllers, added setup flags and autogenerate
package.json => new version umber

**Comment by Apollon77** [comment]
please update your fork/local repo with the version from the main repository ... it seems that you did changes in comparable places as other commits on the "Master" branch ... so these are conflicting now with your changes.

By merging the master back into your fork your should get to see and fix all those conflicts

**Comment by gemu2015** [comment]
hi bluefox

sorry i forgot to mention led_mode

Led_mode is only created for led controllers

and has the following bits defined:

1 = exor for white leds and color leds  => if white leds are switched on, color leds are switched off and vice versa (default on)
2 = allow for color read from MQTT (default off)

due to the fact that tasmota modifies the color value you send via MQTT according to the dimmer value you get a state change, if you read color again.
this introduces a ping pong effect together with farbtastic because farbtastic also rewrites color after reading according to its grafical accuracy

so i made color write only as default. so farbtastic now works without any ping pong effect.

however with your latest changes you removed the ledflag options partially

**Comment by GermanBluefox** [comment]
Thank you for information.
I am still refactoring the code. I don't like bits as the config for end
user and want to cache the flags.
After I will finish, i ask you to check the code one more time.

пт, 15 июн. 2018 г., 7:52 gemu <notifications@github.com>:

**Comment by gemu2015** [comment]
led_mode is only for special test purposes. the default should fit with almost any user.

if you refactor the code, do you have an explanation to the memory behavior of the adapter ?

the memory footprint constantly increases (in my case to about 130 MB,it depends on the number of devices connected)

this is much more then i would expect.  

until now i could not identify the leak

**Pull request merged**
